# Setups
title:            Qinye Li
tagline:          
email:            qinyeli@umich.edu
description: 
url:              "http://qinyeli.github.io/"
baseurl:          /
github_username:  qinyeli
author:
  name:           "Qinye Li"
  url:            qinyeli.github.io

# Build settings
markdown:         kramdown
kramdown:
  input:          GFM # Enable GitHub Flavored Markdown (fenced code blocks)
highlighter:      rouge

# Dependencies
#markdown:        redcarpet
#highlighter:     pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
paginate:         5

# Gems
gems:            [jekyll-paginate, jekyll-gist]
